import{a as d,S as g,i as n}from"./assets/vendor-Dy2ZTtfi.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p="https://pixabay.com/api/",h="51361709-3ae7eddc83ad637b7c3fc8345";function y(i){const s=new URLSearchParams({key:h,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9});return d.get(`${p}?${s}`).then(r=>r.data).catch(r=>(iziToast.error({title:"Error",message:"Failed to retrieve image. Please try again later.",position:"topRight",timeout:4e3}),{hits:[]}))}const u=document.querySelector(".js-gallery"),m=document.querySelector(".loader");let l=null;function L(i){f();const s=i.map(({largeImageURL:r,webformatURL:o,tags:e,...t})=>{const a=["Likes","Views","Comments","Downloads"].map(c=>`
            <li class="images-info-item">
              <h3 class="images-info-subtitle">${c}</h3>
              <p class="images-info-value">${t[c.toLowerCase()]}</p>
            </li>`).join("");return`<li class="gallery-item">
          <a class="gallery-link" href="${r}">
            <img class="gallery-image" src="${o}" alt="${e}" />
            <ul class="images-info-list">${a}</ul>
          </a>
        </li>`}).join("");u.innerHTML=s,x()}function f(){u.innerHTML=""}function b(){m.classList.remove("hidden")}function S(){m.classList.add("hidden")}function x(){l?l.refresh():l=new g(".js-gallery a",{captionsData:!1,captionDelay:500,doubleTapZoom:1.2,maxZoom:4,disableScroll:!0})}const $=document.querySelector(".js-form");$.addEventListener("submit",T);function T(i){i.preventDefault();const r=i.currentTarget.elements["search-text"].value.trim();if(!r){n.error({title:"Error",message:"field must not be empty",position:"topRight"});return}f(),b(),y(r).then(o=>{o.hits.length?L(o.hits):n.warning({title:"⚠️ Warning",message:`Sorry, there are no images matching your "${r}". Please try again!`,position:"topRight",timeout:4e3})}).catch(o=>{n.error({title:"Error",message:o.message,position:"topRight"})}).finally(()=>{i.target.reset(),S()})}
//# sourceMappingURL=index.js.map
